CREATE SEQUENCE USER_SEQ
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 500
    CYCLE NOORDER;

CREATE SEQUENCE URL_SEQ
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 500
    CYCLE NOORDER;

CREATE TABLE USER_CLIENT
(
    ID       NUMBER(10, 0) NOT NULL,
    USERNAME VARCHAR(50)   NOT NULL,
    PASSWORD VARCHAR(50)   NOT NULL,
    EMAIL    VARCHAR(50)   NOT NULL,
    ACTIVE   NUMBER(10, 0) DEFAULT 0,
    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT UK_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE URL
(
    ID          NUMBER(10, 0) NOT NULL,
    URI         VARCHAR(255)  NOT NULL,
    COUNT       NUMBER(10, 0) DEFAULT 0,
    USER_ID     NUMBER(10, 0) NOT NULL,
    CREATE_TIME DATE          NOT NULL,
    CONSTRAINT PK_URL PRIMARY KEY (ID),
    CONSTRAINT FK_USER_URL FOREIGN KEY (USER_ID) REFERENCES USER_CLIENT (ID)
);