CREATE TABLE USER_CLIENT
(
    ID       NUMBER (10,0) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT UK_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE URL
(
    ID        NUMBER (10,0) NOT NULL,
    URI       VARCHAR(255) NOT NULL,
    THRESHOLD NUMBER (10,0) NOT NULL,
    USER_ID   NUMBER (10,0) NOT NULL,
    CONSTRAINT PK_URL PRIMARY KEY (ID),
    CONSTRAINT FK_USER_URL FOREIGN KEY (USER_ID) REFERENCES USER_CLIENT (ID)
);

CREATE TABLE TERMINAL
(
    ID             NUMBER (10, 0) NOT NULL,
    STATUS_CODE    NUMBER (10,0),
    FAILURE_REASON VARCHAR(225),
    URL_ID         NUMBER (10,0) NOT NULL,
    REQUEST_TIME   DATE NOT NULL,
    CONSTRAINT PK_TERMINAL PRIMARY KEY (ID),
    CONSTRAINT FK_URL_TERMINAL FOREIGN KEY (URL_ID) REFERENCES URL (ID)
);