CREATE USER TEST_ADMIN IDENTIFIED BY Aa123456;
GRANT ALL PRIVILEGES TO TEST_ADMIN;
GRANT CREATE SESSION TO TEST_ADMIN;
GRANT EXECUTE ANY PROCEDURE TO TEST_ADMIN;
GRANT UNLIMITED TABLESPACE TO TEST_ADMIN;
